project:
  type: website

website:
  title: "High Leverage Data Points"
  description: "Random things I've found interesting"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/joeycouse
      - icon: linkedin
        href: https://www.linkedin.com/in/joshua-couse

format:
  html:
    theme: cosmo
    css: styles.css



