project:
  type: website
  output-dir: docs

website:
  title: "High Leverage Data Points"
  description: "My public journey through life and data science"
  page-footer: 
    center: The views expressed in this blog are those of the author and do not necessarily reflect the official policy or position of the Air Force, the Department of Defense, or the U.S. Government.
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/joeycouse
      - icon: linkedin
        href: https://www.linkedin.com/in/joshua-couse
  

format:
  html:
    theme: theme.scss



